### PR TITLE
make change to make transform occur on each batch as called

### PR DESCRIPTION
**Pull request by jperez999**
This PR moves the transform from the background thread to the main thread. And it makes sure that the transforms are only called on the batches as they are called for in the iterator. This PR also requires the following core pr to go in first: https://github.com/NVIDIA-Merlin/core/pull/219

### CODE REVIEW

**Comment by karlhigley** [comment]
@jperez999 What makes this better than transforming the tensors? Is it memory usage?

**Comment by jperez999** [comment]
> @jperez999 What makes this better than transforming the tensors? Is it memory usage?

Yes, because otherwise we are running it on ALL the batches for the chunk at the same time. We don't want that. especially not for pretrained embeddings. Atleast that was the design we were all expecting. I didn't execute this correctly first time around.

**Comment by oliverholworthy** [comment]
> running it on ALL the batches for the chunk at the same time

The `_handle_tensors` method called here looks like it's called in generator here so it might not make a difference in terms of the amount of data it's processing up front (i.e. not on a whole chunk/partition at once)

https://github.com/NVIDIA-Merlin/dataloader/blob/v0.0.4/merlin/dataloader/loader_base.py#L477

**Comment by jperez999** [comment]
Closing this because the individual transforms per batch are handled in the background thread... but are still at a per batch basis and only as they are called. Because batches are created using a generator.

**Pull request closed without merging**
